name: post_processing_agent_py2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - pip
  - pytest
  - pytest-cov
  - pytest-mock
  - pip:
    - stompest==2.1.6
# needed for wheel - add when switching to python3
#  - build
